name: "Simple Security Scan"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: |
          npm audit --audit-level=high
          npm audit --audit-level=critical

      - name: Check for known vulnerabilities
        run: |
          npx audit-ci --config .audit-ci.json || echo "Audit completed with findings"

      - name: Run ESLint security check
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx --config eslint.config.mjs || echo "ESLint completed with findings"
